import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,createUserWithEmailAndPassword,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,doc,setDoc,getDoc,collection,addDoc,getDocs,query,where,limit}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
const firebaseConfig={apiKey:"BURAYA_API_KEY",authDomain:"BURAYA.firebaseapp.com",projectId:"BURAYA",storageBucket:"BURAYA.firebasestorage.app",messagingSenderId:"BURAYA",appId:"BURAYA"};
const ready=!Object.values(firebaseConfig).some(x=>x.startsWith("BURAYA"));let auth,db,mode="login",watch=null;
if(ready){const app=initializeApp(firebaseConfig);auth=getAuth(app);db=getFirestore(app)}else console.warn("Firebase config bekleniyor.");
const $=x=>document.getElementById(x),toast=t=>{const x=$("toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",2500)};
$("loginTab").onclick=()=>{mode="login";$("loginTab").classList.add("on");$("registerTab").classList.remove("on");$("authSubmit").textContent="Giriş Yap"};
$("registerTab").onclick=()=>{mode="register";$("registerTab").classList.add("on");$("loginTab").classList.remove("on");$("authSubmit").textContent="Kayıt Ol"};
$("authForm").onsubmit=async e=>{e.preventDefault();if(!ready){$("msg").textContent="Firebase bağlantısı henüz eklenmedi.";return}try{const e=$("email").value,p=$("password").value;if(mode==="login")await signInWithEmailAndPassword(auth,e,p);else await createUserWithEmailAndPassword(auth,e,p)}catch(x){$("msg").textContent=x.message}};
onAuthStateChanged(auth||{},u=>{if(u){$("auth").style.display="none";$("app").style.display="block";$("logout").style.display="block";loadHistory(u.uid)}else{$("auth").style.display="block";$("app").style.display="none";$("logout").style.display="none"}});
$("logout").onclick=()=>signOut(auth);
$("create").onclick=async()=>{if(!auth?.currentUser)return;const name=$("familyName").value||"Ailem",code=Math.random().toString(36).slice(2,8).toUpperCase(),ref=doc(collection(db,"families"));await setDoc(ref,{name,code,ownerId:auth.currentUser.uid,createdAt:Date.now()});await setDoc(doc(db,"users",auth.currentUser.uid),{familyId:ref.id,email:auth.currentUser.email},{merge:true});$("familyInfo").innerHTML=`<b>${name}</b><br>Davet kodu: <strong>${code}</strong>`;toast("Aile oluşturuldu.")};
$("join").onclick=async()=>{const s=await getDocs(query(collection(db,"families"),where("code","==",$("code").value.trim().toUpperCase()),limit(1)));if(s.empty){toast("Kod bulunamadı.");return}await setDoc(doc(db,"users",auth.currentUser.uid),{familyId:s.docs[0].id},{merge:true});toast("Aileye katıldınız.")};
function sharing(on){$("status").textContent=on?"● Konum paylaşımı açık":"● Konum paylaşımı kapalı";$("status").style.color=on?"#63e6a8":"#aaa"}
async function save(p){if(!db||!auth?.currentUser)return;await addDoc(collection(db,"locations"),{uid:auth.currentUser.uid,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,createdAt:Date.now()});const pin=$("pin");pin.style.display="block";pin.style.left="50%";pin.style.top="50%";await loadHistory(auth.currentUser.uid)}
function start(){if(!navigator.geolocation){toast("Tarayıcı konumu desteklemiyor.");return}navigator.geolocation.getCurrentPosition(save,()=>toast("Konum izni alınamadı."),{enableHighAccuracy:true});watch=navigator.geolocation.watchPosition(save,()=>{}, {enableHighAccuracy:true,maximumAge:10000});sharing(true)}
$("share").onclick=()=>{start();toast("Konum paylaşımı açıldı.")};$("locate").onclick=start;$("stop").onclick=()=>{if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;sharing(false);toast("Paylaşım durduruldu.")};
async function loadHistory(uid){if(!db)return;try{const s=await getDocs(query(collection(db,"locations"),where("uid","==",uid),limit(10)));$("historyList").innerHTML=s.empty?"Henüz kayıt yok.":s.docs.map(d=>`<div class="historyItem">${new Date(d.data().createdAt).toLocaleString("tr-TR")}</div>`).join("")}catch(e){$("historyList").textContent="Geçmiş için Firestore ayarı gerekiyor."}}